# Generated by Django 5.1.6 on 2025-02-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', ' Admin'), ('user', 'User'), ('doctor', 'Doctor')], default='user', max_length=50),
        ),
    ]
